# These are supported funding model platforms

open_collective: faisalsayed10
ko_fi: faisalsayed10
liberapay: faisalsayed10
custom: ['https://www.buymeacoffee.com/faisalsayed10', 'https://www.buymeacryptocoffee.xyz/0xe91986533777df9eced01458abbde9599c5cc50f']
